# -*- mode: ruby -*-

# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # Turn off shared folders
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

  # auth vm definition
  config.vm.define "agave.auth" do |auth|
      auth.vm.box = "centos/7"
      auth.vm.hostname = "auth"

      auth.vm.provider "virtualbox" do |v|
          v.customize [ "modifyvm", :id, "--cpus", "1" ]
          v.customize [ "modifyvm", :id, "--memory", "2048" ]
          # handle automatic clock skew fix when box is resumed after long sleeps.
          # without this ntpd will not catch up on its own and you have to run
          # sudo ntpdate ntp.ubuntu.com to resync clocks
          v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
      end

      auth.vm.network "private_network", ip: "192.168.205.10"
  end

  # core api vm definition
  config.vm.define "agave.core.core_api" do |core|
      core.vm.box ="centos/7"
      core.vm.hostname = "core"

      core.vm.provider "virtualbox" do |v|
          v.customize [ "modifyvm", :id, "--cpus", "2" ]
          v.customize [ "modifyvm", :id, "--memory", "3072" ]
          # handle automatic clock skew fix when box is resumed after long sleeps. 
          # without this ntpd will not catch up on its own and you have to run
          # sudo ntpdate ntp.ubuntu.com to resync clocks
          v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
      end

      core.vm.network "private_network", ip: "192.168.205.11"
  end
  
  # core worker vm definition
  config.vm.define "agave.core.core_workers" do |core|
      core.vm.box ="centos/7"
      core.vm.hostname = "core"

      core.vm.provider "virtualbox" do |v|
          v.customize [ "modifyvm", :id, "--cpus", "2" ]
          v.customize [ "modifyvm", :id, "--memory", "4196" ]
          # handle automatic clock skew fix when box is resumed after long sleeps. 
          # without this ntpd will not catch up on its own and you have to run
          # sudo ntpdate ntp.ubuntu.com to resync clocks
          v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
      end

      core.vm.network "private_network", ip: "192.168.205.13"
  end

  # db vm definition
  config.vm.define "agave.db" , primary: true do |db|
      db.vm.box = "centos/7"
      db.vm.hostname = "db"

      db.vm.provider "virtualbox" do |v|
          v.customize [ "modifyvm", :id, "--cpus", "1" ]
          v.customize [ "modifyvm", :id, "--memory", "1024" ]
          # handle automatic clock skew fix when box is resumed after long sleeps. 
          # without this ntpd will not catch up on its own and you have to run
          # sudo ntpdate ntp.ubuntu.com to resync clocks
          v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
      end

      db.vm.network "private_network", ip: "192.168.205.12"
  end

end
