---
# tasks file for roles/jenkins_host

- name: "Install Jenkins custom configurations"
  include_tasks: install_jenkins_custom_config.yml
  become: yes
  become_user: jenkins

- name: "Deploy Jenkins reverse proxy"
  include_tasks: install_jenkins_reverse_proxy.yml
  become: yes
  become_user: apim

- name: "Install Agave deployer source on host"
  include_tasks: install_deployer.yml
  become: yes
  become_user: jenkins
