---

- name: Compile docker_compose template
  template: src=docker-compose-nosql.yml dest=/home/apim/docker-compose-nosql.yml
  sudo: yes
  sudo_user: apim

- name: start the containers with docker compose
  shell: docker-compose -f docker-compose-nosql.yml up -d  chdir=/home/apim
  sudo: yes
  sudo_user: apim
