---
################################################################################
#
#   AUTH VARIABLES
#   These can be read from the standard openstack environment
#   variables if present in the runtime environment.
#
#   os_authurl
#   domain_name
#   project_name
#   username
#   password
#
#   REQUIRED VARIABLES
#
#   os_vm_name
#   os_region
#   os_flavor
#   os_zone
#   os_image
#   os_keyname
#   os_securitygroup
#   os_network
#
#   OPTIONAL VARIABLES
#   os_ip_address - Set ip if you'd like to assign an existing floating ip address
#   os_skip_floating_ip - True to completely skip assigning any floating ip.
#                       This is helpful when the cloud provider assigns static
#                       ip on every instance by default.
#
################################################################################

- name: Create OpenStack VM
  os_server:
    state: present
    auth:
        auth_url: "{{os_authurl}}"
        domain_name: "{{os_domain}}"
        project_name: "{{os_project}}"
        username: "{{os_username}}"
        password: "{{os_password}}"
    name: "{{os_vm_name}}"
    region_name: "{{os_region}}"
    flavor: "{{os_flavor}}"
    availability_zone: "{{os_zone}}"
    image: "{{os_image}}"
    key_name: "{{os_keyname}}"
    security_groups: "{{ os_auth_security_group|join(',') + ',' if os_auth_security_group|len > 0 else ''}}default"
    network: "{{os_network}}"
    auto_ip: "{{ 'yes' if os_instance_ip_address is undefined and os_skip_floating_ip == False else 'no'}}"
    meta:
      group: "{{os_instance_group}}"
      extra_groups: "{{os_instance_extra_groups}}"
      environment: "{{agave_namespace|default('')}}"
      tenant: "{{agave_namespace|default('')}}"
      ansible_user: "{{os_instance_username}}"
      ansible_ssh_private_key_file: "{{os_key_file_src}}"
    wait: yes
    timeout: 300

- name: Assign the provided Floating IP address to the VM
  os_floating_ip:
    state: present
    auth:
        auth_url: "{{os_authurl}}"
        domain_name: "{{os_domain}}"
        project_name: "{{os_project}}"
        username: "{{os_username}}"
        password: "{{os_password}}"
    server: "{{os_vm_name}}"
    region_name: "{{os_region}}"
    floating_ip_address: {{os_ip_address}}
    reuse: yes
    wait: yes
    timeout: 300
  when: os_instance_ip_address is defined and os_skip_floating_ip == False
