version: '2'

services:

  php_api:
    hostname: agaveapi.co
    mem_limit: 1024m
    restart: "always"
    environment:
  #    - 'NEWRELIC_LICENSE_KEY=25c2203d010d177c9dde8eb03853dfa720f31f33'
      - 'NEWRELIC_ENVIRONMENT=prod'
      - 'AGAVE_ENVIRONMENT=prod'
      - 'IPLANT_SLAVE_MODE=false'
      - 'IPLANT_DEDICATED_TENANT_ID=!iplantc.org'
      - 'IPLANT_DRAIN_ALL_QUEUES=false'
      - 'IPLANT_MAX_PAGE_SIZE=300'
      - 'IPLANT_DEFAULT_PAGE_SIZE=100'
      - 'MYSQL_HOST=api.db.prod.agaveapi.co:3306'
      - 'MYSQL_PORT=3306'
      - 'MYSQL_USERNAME=agavestats'
      - 'MYSQL_PASSWORD=KvN8zbgTtlv4'
      - 'MYSQL_DATABASE=agave-api'
      - 'FOUNDATION_MYSQL_HOST=api.db.prod.agaveapi.co:3306'
      - 'FOUNDATION_MYSQL_PORT=3306'
      - 'FOUNDATION_MYSQL_USERNAME=agavestats'
      - 'FOUNDATION_MYSQL_PASSWORD=KvN8zbgTtlv4'
      - 'FOUNDATION_MYSQL_DATABASE=iplant-api'
      - 'IPLANT_METADATA_DB_HOST=nosql.prod.agaveapi.co'
      - 'IPLANT_METADATA_DB_PORT=9000'
      - 'IPLANT_METADATA_DB_USER=wcs'
      - 'IPLANT_METADATA_DB_PWD=q2xViFmkEuxm'
      - 'IPLANT_TENANTS_SERVICE=https://agaveapi.co/tenants'
      - 'IPLANT_STATS_SERVICE=https://agaveapi.co/stats/v2'
      - 'IPLANT_LOG_SERVICE=http://api-prod-agave.tacc.utexas.edu/logging'
      - 'IPLANT_NOTIFICATION_SERVICE_QUEUE=prod.notifications.queue'
      - 'IPLANT_NOTIFICATION_SERVICE_TOPIC=prod.notifications.topic'
      - 'IPLANT_NOTIFICATION_FAILED_DB_HOST=nosql.prod.agaveapi.co'
      - 'IPLANT_NOTIFICATION_FAILED_DB_PORT=9000'
      - 'IPLANT_NOTIFICATION_FAILED_DB_USER=wcs'
      - 'IPLANT_NOTIFICATION_FAILED_DB_PWD=q2xViFmkEuxm'
      - 'IPLANT_NOTIFICATION_FAILED_DB_SCHEME=api'
      - 'IPLANT_MESSAGING_HOST=queue.prod.agaveapi.co'
      - 'IPLANT_MESSAGING_PORT=11300'
      - 'MAIL_SMTPS_PROVIDER=SMTP'
      - 'MAIL_SMTPS_HOST=relay.tacc.utexas.edu'
      - 'MAIL_SMTPS_AUTH=False'
      - 'MAIL_SMTPS_PORT=25'
      - 'MAIL_SMTPS_USER='
      - 'MAIL_SMTPS_PASSWD='
      - 'MAIL_SMTPS_FROM_NAME="Agave Notification Service"'
      - 'MAIL_SMTPS_FROM_ADDRESS="no-reply@agaveapi.co"'
      - 'REALTIME_PROVIDER=fanout'
      - 'REALTIME_URL=https://api.fanout.io/realm'
      - 'REALTIME_REALM_ID=48e3f6fe'
      - 'REALTIME_REALM_KEY=BXCsA390uvkpEYOEx+bp4Q=='
  #    - 'LOG_TARGET_STDOUT=0'
      - 'SSL_CERT=/ssl/api_prod_agaveapi_co_cert.cer'
      - 'SSL_KEY=/ssl/api.prod.agaveapi.co.2015-11-11.key'
      - 'SSL_CA_CERT=/ssl/api_prod_agaveapi_co.cer'
    volumes:
      - './ssl:/ssl:ro'
