---
- name: Install logrotate
  action: "{{ansible_pkg_mgr}} pkg=logrotate state=present"
  when: logrotate_scripts is defined and (logrotate_scripts|length) > 0
  become: yes
  become_user: root
  become_method: sudo

- name: Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{logrotate_scripts}}"
  when: logrotate_scripts is defined
  become: yes
  become_user: root
  become_method: sudo
