---
################################################################################
#
#   REQUIRED VARIABLES
#
#   os_username
#   os_password
#   os_authurl (https://iu.jetstream-cloud.org/dashboard/auth/login/)
#   os_domain
#   os_project
#
################################################################################

- name: Create OpenStack Network
  os_network:
    name: "{{ os_network }}"
    state: present
    admin_state_up: True
    external: False
    shared: False
    auth:
        auth_url: "{{os_authurl}}"
        domain_name: "{{os_domain}}"
        project_name: "{{os_project}}"
        username: "{{os_username}}"
        password: "{{os_password}}"
    wait: yes
  tags:
    - network
    - openstack

- name: Create OpenStack Subnet
  os_subnet:
    name: "{{ os_subnet }}"
    network_name: "{{ os_network }}"
    state: present
    ip_version: 4
    cidr: "{{ os_network_cidr|default('10.10.10.0/24') }}"
    allocation_pool_start: "{{ os_network_allocation_pool_start|default('10.10.10.2') }}"
    allocation_pool_end: "{{ os_network_allocation_pool_end|default('10.10.10.254') }}"
    gateway_ip: "{{ os_network_gateway_ip|default('10.10.10.1') }}"
    enable_dhcp: True
    auth:
        auth_url: "{{os_authurl}}"
        domain_name: "{{os_domain}}"
        project_name: "{{os_project}}"
        username: "{{os_username}}"
        password: "{{os_password}}"
    wait: yes
  tags:
    - subnet
    - openstack
  register: agave_subnet
#
#
#- name: Query OpenStack Subnet
#  os_subnets_facts:
#    name: "{{ os_subnet }}"
#    auth:
#        auth_url: "{{os_authurl}}"
#        domain_name: "{{os_domain}}"
#        project_name: "{{os_project}}"
#        username: "{{os_username}}"
#        password: "{{os_password}}"
#    wait: yes
#  tags:
#    - subnets
#    - security_group
#    - openstack


- name: Create OpenStack Router
  os_router:
    name: "{{agave_namespace}}_router"
    state: present
    interfaces:
        - "{{os_subnet}}"
    auth:
        auth_url: "{{os_authurl}}"
        domain_name: "{{os_domain}}"
        project_name: "{{os_project}}"
        username: "{{os_username}}"
        password: "{{os_password}}"
    wait: yes
  tags:
    - router
    - openstack

- name: Query OpenStack Network
  os_networks_facts:
    name: "{{ os_network }}"
    auth:
        auth_url: "{{os_authurl}}"
        domain_name: "{{os_domain}}"
        project_name: "{{os_project}}"
        username: "{{os_username}}"
        password: "{{os_password}}"
    wait: yes
  tags:
    - security_group
    - openstack

- name: Query OpenStack Subnet
  os_subnets_facts:
    name: "{{ os_subnet }}"
    auth:
        auth_url: "{{os_authurl}}"
        domain_name: "{{os_domain}}"
        project_name: "{{os_project}}"
        username: "{{os_username}}"
        password: "{{os_password}}"
    wait: yes
  tags:
    - security_group
    - openstack

- name: Create Basic Firewall Rules
  os_security_group_rule:
    auth_type: password
    auth:
        auth_url: "{{os_authurl}}"
        domain_name: "{{os_domain}}"
        project_name: "{{os_project}}"
        username: "{{os_username}}"
        password: "{{os_password}}"
    security_group: default
    state: present
    direction: "{{item.direction}}"
    ethertype: "{{item.ethertype}}"
    protocol: "{{item.protocol}}"
    port_range_min: "{{item.port_range_min}}"
    port_range_max: "{{item.port_range_max}}"
    remote_ip_prefix: "{{item.remote_ip_prefix}}"
  with_items:
    - { direction: ingress , ethertype: IPv4 , protocol: tcp , port_range_min: 22 , port_range_max: 22 , remote_ip_prefix: 0.0.0.0/0 }
  tags:
    - security_group
    - openstack

- name: Create VM Keys
  os_keypair:
    name: "{{os_keyname}}"
    public_key_file: "{{os_key_file}}"
    state: present
    auth_type: password
    auth:
        auth_url: "{{os_authurl}}"
        domain_name: "{{os_domain}}"
        project_name: "{{os_project}}"
        username: "{{os_username}}"
        password: "{{os_password}}"
  tags:
    - keys
    - openstack