# Starts a vanilla containerized AWX stack

---

- name: stop the awx stack containers
  shell: /usr/local/bin/docker-compose stop
  args:
    chdir: "{{role_path}}/files"
  when: stop_awx_containers
  ignore_failure: True
  environment:
    COMPOSE_HTTP_TIMEOUT: 2000

- name: clear the awx stack containers
  shell: /usr/local/bin/docker-compose down
  args:
    chdir: "{{role_path}}/files"
  when: clear_awx_containers
  environment:
    COMPOSE_HTTP_TIMEOUT: 2000

- name: start the awx stack containers
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{role_path}}/files"
  when: start_awx_containers
  environment:
    COMPOSE_HTTP_TIMEOUT: 2000
