---

- name: Ensure ssl directory exists for remote self-signed TLS certs
  file:
    path: "/home/apim/auth-services/{{ tenant_id }}/httpd"
    state: directory
  become: yes
  become_user: apim
  become_method: sudo

- name: Generate RSA Key
  command: openssl genrsa \
    -out "/home/apim/auth-services/{{ tenant_id }}/httpd/{{cert_key_file|default('apache.key')}}" 2048
  args:
    creates: "/home/apim/auth-services/{{ tenant_id }}/httpd/{{cert_key_file|default('apache.key')}}"
  become: yes
  become_user: apim
  become_method: sudo

- name: Generate CSR
  command: openssl req \
    -new \
    -subj "/C/US/ST=TX/L=Austin/O=AgavePlatform/CN={{host}}" \
    -key "/home/apim/auth-services/{{ tenant_id }}/httpd/{{cert_key_file|default('apache.key')}}" \
    -out "/home/apim/auth-services/{{ tenant_id }}/httpd/{{cert_key_file|default('apache.key')}}.csr"
  args:
    creates: "/home/apim/auth-services/{{ tenant_id }}/httpd/{{cert_key_file|default('apache.key')}}.csr"
  become: yes
  become_user: apim
  become_method: sudo

- name: Generate self-signed OpenSSL certificate
  command: openssl req \
    -x509 \
    -days 1825 \
    -key "/home/apim/auth-services/{{ tenant_id }}/httpd/{{cert_key_file|default('apache.key')}}" \
    -in "/home/apim/auth-services/{{ tenant_id }}/httpd/{{cert_key_file|default('apache.key')}}.csr" \
    -out "/home/apim/auth-services/{{ tenant_id }}/httpd/{{cert_file|default('apache.crt')}}"
  args:
    creates: "/home/apim/auth-services/{{ tenant_id }}/httpd/{{cert_file|default('apache.crt')}}"
  become: yes
  become_user: apim
  become_method: sudo
