---
################################################################################
#
#   REQUIRED VARIABLES
#
#   os_zone
#   os_image
#   os_keyname
#
################################################################################

- name: Delete OpenStack VM
  os_server:
    state: absent
    name: "{{os_vm_name}}"
#    region_name: "{{os_region}}"
    flavor: "{{os_flavor}}"
#    availability_zone: "{{os_zone}}"
    image: "{{os_image}}"
    key_name: "{{os_keyname}}"
