---

# should existing images be removed, or just pull and run the new one?
remove_all_togo_containers: False

# Should a set of client keys be generated for the app based on the tenant deployment settings?
agave_togo_static_generate_key: False

# url of the togo instance.
agave_togo_static_url: "https://togo.sandbox.agaveplatform.org"
agave_togo_tenants_api_url: "https://sandbox.agaveplatform.org/tenants/v2"

# provide implicit.js configuration options as yaml objects. These should correspond 1 for 1 with
# the JSON configuration in togo's auth/scripts/implicit.js file.
agave_togo_static_implicit_auth_config:
    "sandbox":
        client_key: "abcdefg"
        callback_url: "https://togo.sandbox.agaveplatform.org/auth/"
        scope: "PRODUCTION"
        project_url: "https://agaveplatform.org/"
        support_url: "https://slackin.agaveapi.co/"
        signup_url: "https://sandbox.agaveplatform.org/create_account"
