---

- include_vars: agave_core_configs/{{ core_config_file }}.yml
- include_vars: agave_core_configs/{{ core_config_file }}_passwords

- name: ensure migrations directory present
  file:
    path: "/home/apim/core-migrations"
    state: "directory"
    owner: apim
    mode: 0750
  become: yes
  become_user: apim

- name: compile compose templates
  template:
    src: "migrations.yml.j2"
    dest: "/home/apim/core-migrations/migrations.yml"
    owner: apim
    mode: 0640
  become: yes
  become_user: apim

- name: compile flyway.conf templates
  template:
    src: "flyway.conf.j2"
    dest: "/home/apim/core-migrations/flyway.conf"
    owner: apim
    mode: 0644
  become: yes
  become_user: apim

- name: run the migration
  shell: |
    docker run -i --rm -v $(pwd)/flyway.conf:/source/flyway-4.1.1/conf/flyway.conf \
          --entrypoint="/source/flyway-4.1.1/flyway" \
          agaveapi/agave-migrations:{{ agave_core_version }} \
          {{ core_migrations_command }}
  args:
    chdir: "/home/apim/core-migrations"
  become: yes
  become_user: apim
  environment:
    COMPOSE_HTTP_TIMEOUT: 2000

- name: update tenant definition in the core db
  shell: |
    docker run -i --rm mysql:5.6 \
          mysql -A -u{{ mysql_core_user }} -p{{ mysql_core_password }} -h{{ mysql_core_host }} -P{{ mysql_core_port }} \
          -e  "UPDATE \`tenants\` SET \`base_url\` = 'https://{{ host }}/', \`name\` = 'Agave {{ tenant_id }} Tenant',  \`tenant_id\` = '{{ tenant_id }}' WHERE \`id\` = '1';" agave-api
  args:
    chdir: "/home/apim/core-migrations"
  become: yes
  become_user: apim


