# General purpose role for making the target server into a docker host.
# Installs the latest docker binary as well as the latest docker compose binary.

---

- name: Add docker group
  group: name=docker state=present
  become: yes

- name: Add user to docker group
  user: name={{ agave_linux_user_name }} generate_ssh_key=yes state=present groups=docker
  become: yes

#- name: Flush iptables INPUT Chain
#  command: /usr/sbin/iptables -F INPUT
#  sudo: yes
#  when: "{{ update_docker_version }}"

#- name: Flush iptables FORWARD Chain
#  command: /usr/sbin/iptables -F FORWARD
#  sudo: yes
#  when: "{{ update_docker_version }}"

- name: Ensure docker is not running
  service: name=docker state=stopped
  become: yes
  when: update_docker_version or update_docker_compose_version
  ignore_errors: yes

- include_tasks: main-ubuntu.yml
  become: yes
  when: ansible_os_family == "Debian"

- include_tasks: main-centos.yml
  become: yes
  when: ansible_os_family == "RedHat"

- name: Ensure docker is not running
  service: name=docker state=stopped
  become: yes
  when: update_docker_version or update_docker_compose_version

- name: Install docker compose
  shell: curl -skL -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
  become: yes
  when: update_docker_compose_version

- name: Set permissions on docker compose binary
  file:
    state: file
    mode: 0755
    path: /usr/local/bin/docker-compose
  become: yes
  when: update_docker_compose_version


# todo - need to check this
- name: Flush iptables INPUT Chain
  command: /usr/sbin/iptables -F INPUT
#  ignore_errors: yes
  become: yes

- name: Ensure docker is running
  systemd:
    name: docker
    state: started
    daemon_reload: yes
    enabled: yes
  become: yes

# Aliases, completion, helpers for docker and docker compose
- name: Install docker aliases into user's .bashrc.d directory
  shell: curl -skL -o /etc/profile.d/docker.aliases https://gist.githubusercontent.com/deardooley/011ce72d1e2ad3c03045879f0ea41b25/raw/25ff4601c6ec851c3048cfd02e7b9ced80ecbaeb/docker.aliases.sh
  become: yes

- name: Add execute permission to docker aliases
  file:
    path: /etc/profile.d/docker.aliases
    mode: 01755
  become: yes

- name: Install docker-compose bash completion
  shell: curl -skL -o /etc/bash_completion.d/docker-compose https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose
  become: yes

- name: Add execute permission to docker-compose bash completion
  file:
    path: /etc/bash_completion.d/docker-compose
    owner: root
    group: root
    mode: 01755
  become: yes
