---

- name: packages
  yum: pkg={{item}} state=present update_cache=yes
  with_items:
      - nfs-utils
      - rpcbind
  sudo: yes

- name: ensure directories are present
  file: path={{ item.value.dir }} state=directory owner=apim
  with_dict: "{{ exports }}"
  sudo: yes

- name: create mounts for external directories
  mount: src="{{nfs_server_ip }}:{{ item.value.dir }}" name={{ item.value.dir }} state=mounted fstype=nfs
  with_dict: "{{ exports }}"
  sudo: yes
