---
################################################################################
#
#   REQUIRED VARIABLES
#
#   agave_namespace
#
################################################################################

- name: Delete OpenStack Router
  os_router:
    name: "{{agave_namespace}}_router"
    state: absent

- name: Delete OpenStack Subnet
  os_subnet:
    name: "{{agave_namespace}}_subnet"
    network_name: "{{agave_namespace}}_net"
    state: absent

- name: Delete OpenStack Network
  os_network:
    name: "{{agave_namespace}}_net"
    state: absent

- name: Delete VM Keys
  os_keypair:
    name: "{{os_keyname}}"
    state: absent
